# Generated by Django 5.1.3 on 2024-12-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
